export const FETCH_LIGHTS_START = 'FETCH_LIGHTS_START';
export const FETCH_LIGHTS_SUCCESS = 'FETCH_LIGHTS_SUCCESS';
export const FETCH_LIGHTS_FAILURE = 'FETCH_LIGHTS_FAILURE';

export const LOAD_MORE_LIGHTS_START = 'LOAD_MORE_LIGHTS_START';
export const LOAD_MORE_LIGHTS_SUCCESS = 'LOAD_MORE_LIGHTS_SUCCESS';
export const LOAD_MORE_LIGHTS_FAILURE = 'LOAD_MORE_LIGHTS_FAILURE';

export const FETCH_LIGHT_BY_ID_START = 'FETCH_LIGHT_BY_ID_START';
export const FETCH_LIGHT_BY_ID_SUCCESS = 'FETCH_LIGHT_BY_ID_SUCCESS';
export const FETCH_LIGHT_BY_ID_FAILURE = 'FETCH_LIGHT_BY_ID_FAILURE';

export const ADD_LIGHT_TO_BASKET = 'ADD_LIGHT_TO_BASKET';

export const SEARCH_LIGHT = 'SEARCH_LIGHT';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const REMOVE_LIGHT_FROM_BASKET = 'REMOVE_LIGHT_FROM_BASKET';

export const CLEAN_BASKET = 'CLEAN_BASKET';